# 智能体配置文件
# 配置Chat Agent、Action Agent、Memory Agent的参数

chat_agent:
  model: "qwen-7b"
  max_tokens: 2048
  temperature: 0.7

action_agent:
  planning_horizon: 5
  safety_check: true

memory_agent:
  max_history: 100
  learning_rate: 0.01