# 系统配置
system:
  name: "RobotAgent MVP"
  version: "1.0.0"
  debug: true
  log_level: "INFO"

# 服务配置
server:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: true

# Qwen模型配置 - 使用DashScope API
qwen:
  # DashScope API配置
  api_key: "${DASHSCOPE_API_KEY}"  # 从环境变量读取
  model_name: "qwen-max-latest"    # 推荐使用最新模型
  base_url: "https://dashscope.aliyuncs.com/api/v1"
  
  # 生成参数
  max_tokens: 2048
  temperature: 0.1
  top_p: 0.8
  
  # 请求配置
  timeout: 30
  max_retries: 3
  retry_delay: 1.0
  
  # 功能开关
  enable_search: false
  enable_function_call: true
  
  # 系统提示词
  system_prompt: |
    你是一个专业的机器人控制助手，能够将自然语言指令转换为机器人控制命令。
    请根据用户的自然语言输入，解析出对应的机器人动作意图和参数。
    
    输出格式必须是JSON，包含以下字段：
    - intent: 意图类型（如move_to_position, gripper_control等）
    - action: 具体动作（如move_arm, open_gripper等）
    - parameters: 动作参数（如位置坐标、角度等）
    - confidence: 置信度（0-1之间的浮点数）
    
    支持的意图类型：
    - move_to_position: 移动到指定位置
    - gripper_control: 夹爪控制
    - joint_control: 关节控制
    - pick_object: 抓取物体
    - place_object: 放置物体
    - get_current_pose: 获取当前位姿
    - stop_motion: 停止运动
    - go_home: 回到初始位置

# Redis配置
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  decode_responses: true

# 消息队列配置
message_queue:
  channels:
    input: "nlp_input"
    memory: "memory_agent"
    ros2: "ros2_agent"
    status: "system_status"
  message_ttl: 3600  # 消息过期时间（秒）

# ROS2配置
ros2:
  domain_id: 0
  workspace_path: "~/ros2_ws"
  robot_type: "rm65"  # 睿尔曼机械臂型号
  simulation: true
  
  # 机械臂控制参数
  arm_control:
    default_speed: 0.1
    default_acceleration: 0.1
    position_tolerance: 0.01
    orientation_tolerance: 0.1
    
  # 安全限制
  safety:
    workspace_limits:
      x: [-0.8, 0.8]
      y: [-0.8, 0.8]
      z: [0.0, 1.0]
    max_velocity: 0.5
    max_acceleration: 1.0

# 记忆Agent配置
memory_agent:
  storage_path: "./memory_records"
  file_format: "markdown"
  max_file_size: "10MB"
  backup_enabled: true
  backup_interval: 3600  # 备份间隔（秒）

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "./logs"
  max_file_size: "50MB"
  backup_count: 5
  
  # 各组件日志配置
  loggers:
    qwen_service: "INFO"
    memory_agent: "INFO"
    ros2_agent: "INFO"
    message_queue: "DEBUG"

# 性能监控配置
monitoring:
  enabled: true
  metrics_interval: 60  # 指标收集间隔（秒）
  performance_log: "./logs/performance.log"
  
  # 告警阈值
  alerts:
    response_time_threshold: 5.0  # 响应时间阈值（秒）
    error_rate_threshold: 0.1     # 错误率阈值
    memory_usage_threshold: 0.8   # 内存使用率阈值

# 前端配置
frontend:
  static_path: "./frontend/static"
  template_path: "./frontend/templates"
  websocket_enabled: true