# -*- coding: utf-8 -*-

# 系统配置文件 (System Configuration)
# RobotAgent MVP系统级别的核心配置参数
# 作者: RobotAgent开发团队
# 版本: 0.0.1 (Initial Release)
# 更新时间: 2025-08-21
# 基于: CAMEL框架的配置管理标准

# 系统核心配置
# 控制智能体系统的基础运行参数和性能设置
system:
  # 日志级别设置 - 控制系统日志输出的详细程度
  # 可选值: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_level: "INFO"
  
  # 最大并发任务数 - 限制系统同时处理的任务数量
  # 建议值: 根据系统资源调整，默认10个并发任务
  max_concurrent_tasks: 10
  
  # 系统运行模式 - 开发/生产环境配置
  # 可选值: development, production, testing
  environment: "development"
  
  # 智能体状态检查间隔（秒）
  agent_health_check_interval: 30

# 通信系统配置
# 控制智能体间消息传递和协作的参数设置
communication:
  # 消息超时时间（秒）- 消息等待响应的最大时间
  message_timeout: 30
  
  # 重试次数 - 消息发送失败时的重试次数
  retry_attempts: 3
  
  # 消息队列大小 - 每个智能体的消息缓冲区大小
  message_queue_size: 100
  
  # 心跳检测间隔（秒）- 智能体间连接状态检测
  heartbeat_interval: 10

# 输出系统配置
# 控制智能体输出格式和外部接口的参数设置
output:
  # 文本转语音功能开关
  tts_enabled: true
  
  # 动作文件输出格式 - 智能体动作指令的存储格式
  # 可选值: json, yaml, xml
  action_file_format: "json"
  
  # 输出文件编码格式
  file_encoding: "utf-8"
  
  # 输出目录路径（相对于项目根目录）
  output_directory: "src/output"

# 性能监控配置
# 系统性能指标收集和监控的参数设置
performance:
  # 性能监控开关
  monitoring_enabled: true
  
  # 指标收集间隔（秒）
  metrics_collection_interval: 60
  
  # 性能日志保留天数
  performance_log_retention_days: 7

# 安全配置
# 系统安全相关的参数设置
security:
  # API密钥加密开关
  encrypt_api_keys: true
  
  # 会话超时时间（分钟）
  session_timeout_minutes: 30
  
  # 最大登录尝试次数
  max_login_attempts: 3